#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu May 06 00:13:44 EDT 2021
# SW Build 3118627 on Tue Feb  9 05:13:49 MST 2021
#
# Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_project3_behav -key {Behavioral:sim_1:Functional:tb_project3} -tclbatch tb_project3.tcl -view /home/wchen487/Documents/3220_a3/assignment3_part1/tb_project3_behav.wcfg -log simulate.log"
xsim tb_project3_behav -key {Behavioral:sim_1:Functional:tb_project3} -tclbatch tb_project3.tcl -view /home/wchen487/Documents/3220_a3/assignment3_part1/tb_project3_behav.wcfg -log simulate.log

