webtalk_init -webtalk_dir /home/plee304/3220_a3part1/3220_a3/assignment3_part1/assignment3_part1.sim/sim_1/behav/xsim/xsim.dir/tb_project3_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Mar 18 16:43:48 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0912d883-13e1-47fa-8987-8312d65313e5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "16b7547587c5464998e1a9381c170751" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "131" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel Xeon E312xx (Sandy Bridge)" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2100.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "4" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "15 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.24_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "126856_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1159437863 -regid "" -xml /home/plee304/3220_a3part1/3220_a3/assignment3_part1/assignment3_part1.sim/sim_1/behav/xsim/xsim.dir/tb_project3_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/plee304/3220_a3part1/3220_a3/assignment3_part1/assignment3_part1.sim/sim_1/behav/xsim/xsim.dir/tb_project3_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/plee304/3220_a3part1/3220_a3/assignment3_part1/assignment3_part1.sim/sim_1/behav/xsim/xsim.dir/tb_project3_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
